email:
  sent_from : "sender_email_address" 
  email_password : "sender_email_password"

  # [edit] enter receiver email details
  to : ["toemail"]

area_info:
# [edit] enter your district code or pincode
  __district_code : "256" 
  __pincode : "560078"
  
age_limit:
  age_limit : [45]
